version: "3.8"

x-common-variables: &common-variables
  POSTGRES_DB: db
  POSTGRES_TEST_DB: test_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db

volumes:
  postgres-storage:
services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment: *common-variables
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: .
    depends_on:
      - db
    environment:
      <<: *common-variables
      MIX_ENV: dev
    ports:
      - 4000:4000
    volumes:
      - .:/app
    stdin_open: true
    command: ["bash", "/tmp/server_init.sh"]
